<!-- .slide: data-background="#111111" -->

# WyjÄ…tki w call_once

<a href="https://coders.school">
    <img width="500" data-src="../coders_school_logo.png" alt="Coders School" class="plain">
</a>

___
<!-- .slide: style="font-size: .83em" -->

## Zadanie: wyjÄ…tki w call_once

<div class="multicolumn">

<div style="width: 56%;">

```cpp []
class X {
    once_flag once;
    vector<double> values;

    void initializeOne() {
        cout << __FUNCTION__ << '\n';
        call_once(once, [&]{
            cout << "Call once initializeOne\n";
            values = {1.0};
        });
    }

    // ...

    void initializePierdyliard() {
        cout << __FUNCTION__ << '\n';
        call_once(once, [&]{
            cout << "Call once initializePierdyliard\n";
            throw std::bad_alloc{};
            // TODO: Can you fix me?
        });
    }
};
```
<!-- .element: class="fragment fade-in" -->
</div>

<div style="width: 44%;">

<div style="padding: 20px;">

* <!-- .element: class="fragment fade-in" --> SprÃ³buj naprawiÄ‡ problem z rzucaniem wyjÄ…tkÃ³w w call_once
* <!-- .element: class="fragment fade-in" --> Wg <a href="https://en.cppreference.com/w/cpp/thread/call_once">cppreference.com</a>:
  * <!-- .element: class="fragment fade-in" --> <i>If that invocation throws an exception, it is propagated to the caller of call_once, and the flag is not flipped so that another call will be attempted (such call to call_once is known as exceptional)</i>

</div>

```bash
$> g++ 03_exceptional_exclusive_calls.cpp
-lpthread -fsanitize=thread
$> ./a.out
...
initializePierdyliard
Call once initializePierdyliard
terminate called after throwing an instance
of 'std::bad_alloc'
what(): std::bad_alloc
Aborted (core dumped)
```
<!-- .element: class="fragment fade-in" -->

</div>

___
<!-- .slide: style="font-size: .85em" -->

## Zadanie - rozwiÄ…zanie

<div class="multicolumn">

<div style="width: 57%;">

```cpp []
class X {
    once_flag once;
    vector<double> values;

    void initializeOne() {
        cout << __FUNCTION__ << '\n';
        call_once(once, [&]{
            cout << "Call once initializeOne\n";
            values = {1.0};
        });
    }

    // ...

    void initializePierdyliard() try {
        cout << __FUNCTION__ << '\n';
        call_once(once, [&]{
            cout << "Call once initializePierdyliard\n";
            throw std::bad_alloc{};
        });
    } catch (...) { /* ignore exceptions */ }
};
```
<!-- .element: class="fragment fade-in" -->
</div>

<div style="width: 43%;">

<div style="padding: 20px;">

* <!-- .element: class="fragment fade-in" --> SprÃ³buj naprawiÄ‡ problem z rzucaniem wyjÄ…tkÃ³w w call_once
* <!-- .element: class="fragment fade-in" --> Wg <a href="https://en.cppreference.com/w/cpp/thread/call_once">cppreference.com</a>:
  * <!-- .element: class="fragment fade-in" --> If that invocation throws an exception, it is propagated to the caller of call_once, and the flag is not flipped so that another call will be attempted (such call to call_once is known as exceptional)

* <!-- .element: class="fragment fade-in" -->  <b>NIE DA SIÄ˜! (Przynajmniej u mnie ğŸ™‚)</b>

</div>

```bash
$> g++ 03_exceptional_exclusive_calls.cpp
-lpthread -fsanitize=thread
$> ./a.out
...
initializePierdyliard
Call once initializePierdyliard
initializeOne
(hang up)
```
<!-- .element: class="fragment fade-in" -->

</div>

___
<!-- .slide: style="color: #555" -->

## WyjÄ…tki w call_once â€“ bug w implementacji biblioteki standardowej

* JeÅ›li once_flag jest w stanie "wywoÅ‚ana", call_once natychmiast zwraca - return (passive call)
* <!-- .element: style="color: #fff" --> JeÅ›li once_flag jest w stanie "nie wywoÅ‚ana", call_once wykonuje przekazanÄ… funkcjÄ™, przekazujÄ…c do niej dalsze argumenty (active call)
  * JeÅ›li funkcja rzuci wyjÄ…tkiem to jest on propagowany dalej, a `once_flag` nie zostaje ustawiona w stanie "wywoÅ‚ana" (exceptional call), wiÄ™c inny `call_once` moÅ¼e zostaÄ‡ wywoÅ‚any <span style="color: #f33">(przynajmniej w teorii ğŸ™‚) â€“ [bug w implementacji](https://github.com/PaddlePaddle/Paddle/issues/6681), [przykÅ‚ad na cppreference.com](https://en.cppreference.com/w/cpp/thread/call_once#Example) teÅ¼ nie dziaÅ‚a, podobno dziaÅ‚a w MSVC (Visual Studio Compiler)</span>
  * <!-- .element: style="color: #555" --> JeÅ›li funkcja zakoÅ„czy siÄ™ normalnie, once_flag zostaje ustawiona w stan "wywoÅ‚ana" (returning call). Gwarantowane jest, Å¼e wszystkie inne wywoÅ‚ania bÄ™dÄ… pasywne.
* Kilka aktywnych zawoÅ‚aÅ„ na tej samej fladze once_flag jest kolejkowanych.
* JeÅ›li tej samej flagi uÅ¼ywamy do wspÃ³Å‚bieÅ¼nych wywoÅ‚aÅ„ rÃ³Å¼nych funkcji, to nie jest wyspecyfikowane, ktÃ³ra funkcja zostanie zawoÅ‚ana.

___
<!-- .slide: style="color: #bbb" -->

## Przydatne linki

* <!-- .element: class="fragment fade-in" --> <a href="http://www.open-std.org/jtc1/sc22/wg21/docs/papers/2007/n2393.html">C++ Atomic Types and Operations (C++ Standard)</a>
* <!-- .element: class="fragment fade-in" --> <a href="https://en.cppreference.com/w/cpp/language/memory_model">C++ Memory model on cppreference.com</a>
* <!-- .element: class="fragment fade-in" --> <a href="https://en.cppreference.com/w/cpp/atomic/memory_order">std::memory_order on cppreference.com</a>
* <!-- .element: class="fragment fade-in" --> <a href="https://en.cppreference.com/w/cpp/thread/call_once">std::call_once on cppreference.com</a>
* <!-- .element: class="fragment fade-in" --> <a href="https://en.cppreference.com/w/cpp/thread/once_flag">std::once_flag on cppreference.com</a>
  * <!-- .element: class="fragment fade-in" --> <a href="https://github.com/PaddlePaddle/Paddle/issues/6681">STL bug in exception handling in call_once</a>
  * <!-- .element: class="fragment fade-in" --> <a href="https://stackoverflow.com/questions/26985370/stdcall-once-vs-stdmutex-for-thread-safe-initialization">call_once vs mutex on stackoverflow</a>
* <!-- .element: class="fragment fade-in" --> <a href="https://stackoverflow.com/questions/17712001/how-is-meyers-implementation-of-a-singleton-actually-a-singleton">Meyers Singleton on stackoverflow</a>
